// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefIwJFAMamBchKVfgEIm_NHgH3WdmZm8',
    appId: '1:466524808667:web:ed8a0de25a3aa593c3b3fe',
    messagingSenderId: '466524808667',
    projectId: 'flutter-pet-project-f74f4',
    authDomain: 'flutter-pet-project-f74f4.firebaseapp.com',
    storageBucket: 'flutter-pet-project-f74f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5qm98dFgqkXnpKi9CGsKPw0Q3KmRa_TQ',
    appId: '1:466524808667:android:3f2558b649ec64f7c3b3fe',
    messagingSenderId: '466524808667',
    projectId: 'flutter-pet-project-f74f4',
    storageBucket: 'flutter-pet-project-f74f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFcsM-r9xhaKib6uglsWhUpGKanmpQgw',
    appId: '1:466524808667:ios:2b5347338aa63d6cc3b3fe',
    messagingSenderId: '466524808667',
    projectId: 'flutter-pet-project-f74f4',
    storageBucket: 'flutter-pet-project-f74f4.firebasestorage.app',
    iosBundleId: 'com.example.myPetProject',
  );
}
